# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Aunis.ui'
##
## Created by: Qt User Interface Compiler version 6.8.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QDoubleSpinBox, QFrame, QGroupBox,
    QHeaderView, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPlainTextEdit, QPushButton,
    QSizePolicy, QTabWidget, QTableWidget, QTableWidgetItem,
    QWidget)

from AutoComplete import TextEditAutoComplete

class Ui_Aunis(object):
    def setupUi(self, Aunis):
        if not Aunis.objectName():
            Aunis.setObjectName(u"Aunis")
        Aunis.resize(570, 500)
        Aunis.setMinimumSize(QSize(570, 500))
        Aunis.setMaximumSize(QSize(570, 500))
        self.menuAboutHelp = QAction(Aunis)
        self.menuAboutHelp.setObjectName(u"menuAboutHelp")
        self.menuManualHelp = QAction(Aunis)
        self.menuManualHelp.setObjectName(u"menuManualHelp")
        self.menuSaveFile = QAction(Aunis)
        self.menuSaveFile.setObjectName(u"menuSaveFile")
        self.menuLoadFile = QAction(Aunis)
        self.menuLoadFile.setObjectName(u"menuLoadFile")
        self.centralwidget = QWidget(Aunis)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(200, 10, 361, 321))
        font = QFont()
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.scripting_Script = TextEditAutoComplete(self.tab)
        self.scripting_Script.setObjectName(u"scripting_Script")
        self.scripting_Script.setGeometry(QRect(10, 10, 331, 241))
        self.scripting_Run = QPushButton(self.tab)
        self.scripting_Run.setObjectName(u"scripting_Run")
        self.scripting_Run.setGeometry(QRect(180, 260, 75, 24))
        self.scripting_Stop = QPushButton(self.tab)
        self.scripting_Stop.setObjectName(u"scripting_Stop")
        self.scripting_Stop.setGeometry(QRect(260, 260, 75, 24))
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.groupBox_3 = QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 140, 191, 121))
        font1 = QFont()
        font1.setBold(True)
        self.groupBox_3.setFont(font1)
        self.tipman_Yminus = QPushButton(self.groupBox_3)
        self.tipman_Yminus.setObjectName(u"tipman_Yminus")
        self.tipman_Yminus.setGeometry(QRect(70, 80, 60, 24))
        self.tipman_Yminus.setFont(font)
        self.tipman_Xplus = QPushButton(self.groupBox_3)
        self.tipman_Xplus.setObjectName(u"tipman_Xplus")
        self.tipman_Xplus.setGeometry(QRect(120, 50, 60, 24))
        self.tipman_Xplus.setFont(font)
        self.tipman_Xminus = QPushButton(self.groupBox_3)
        self.tipman_Xminus.setObjectName(u"tipman_Xminus")
        self.tipman_Xminus.setGeometry(QRect(20, 50, 60, 24))
        self.tipman_Xminus.setFont(font)
        self.tipman_Yplus = QPushButton(self.groupBox_3)
        self.tipman_Yplus.setObjectName(u"tipman_Yplus")
        self.tipman_Yplus.setGeometry(QRect(70, 20, 60, 24))
        self.tipman_Yplus.setFont(font)
        self.groupBox_4 = QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(210, 140, 131, 121))
        self.groupBox_4.setFont(font1)
        self.tipman_Zminus = QPushButton(self.groupBox_4)
        self.tipman_Zminus.setObjectName(u"tipman_Zminus")
        self.tipman_Zminus.setGeometry(QRect(40, 70, 60, 24))
        self.tipman_Zminus.setFont(font)
        self.tipman_Zplus = QPushButton(self.groupBox_4)
        self.tipman_Zplus.setObjectName(u"tipman_Zplus")
        self.tipman_Zplus.setGeometry(QRect(40, 30, 60, 24))
        self.tipman_Zplus.setFont(font)
        self.groupBox_5 = QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 10, 331, 101))
        self.groupBox_5.setFont(font1)
        self.groupBox_5.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.label_4 = QLabel(self.groupBox_5)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 30, 41, 16))
        self.label_4.setFont(font)
        self.label_5 = QLabel(self.groupBox_5)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(180, 30, 41, 16))
        self.label_5.setFont(font)
        self.label_6 = QLabel(self.groupBox_5)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 60, 41, 16))
        self.label_6.setFont(font)
        self.tipman_dx = QDoubleSpinBox(self.groupBox_5)
        self.tipman_dx.setObjectName(u"tipman_dx")
        self.tipman_dx.setGeometry(QRect(70, 30, 88, 22))
        self.tipman_dx.setFont(font)
        self.tipman_dx.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.tipman_dx.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tipman_dx.setMaximum(99.000000000000000)
        self.tipman_dx.setSingleStep(0.010000000000000)
        self.tipman_dx.setValue(0.100000000000000)
        self.tipman_dy = QDoubleSpinBox(self.groupBox_5)
        self.tipman_dy.setObjectName(u"tipman_dy")
        self.tipman_dy.setGeometry(QRect(230, 30, 88, 22))
        self.tipman_dy.setFont(font)
        self.tipman_dy.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.tipman_dy.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tipman_dy.setMaximum(99.000000000000000)
        self.tipman_dy.setSingleStep(0.010000000000000)
        self.tipman_dy.setValue(0.100000000000000)
        self.tipman_dz = QDoubleSpinBox(self.groupBox_5)
        self.tipman_dz.setObjectName(u"tipman_dz")
        self.tipman_dz.setGeometry(QRect(70, 60, 88, 22))
        self.tipman_dz.setFont(font)
        self.tipman_dz.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tipman_dz.setMaximum(99.000000000000000)
        self.tipman_dz.setSingleStep(0.010000000000000)
        self.tipman_dz.setValue(0.100000000000000)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.external_Interfaces = QTableWidget(self.tab_4)
        if (self.external_Interfaces.columnCount() < 3):
            self.external_Interfaces.setColumnCount(3)
        __qtablewidgetitem = QTableWidgetItem()
        self.external_Interfaces.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        __qtablewidgetitem1.setFont(font);
        self.external_Interfaces.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        __qtablewidgetitem2.setFont(font);
        self.external_Interfaces.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        if (self.external_Interfaces.rowCount() < 4):
            self.external_Interfaces.setRowCount(4)
        __qtablewidgetitem3 = QTableWidgetItem()
        __qtablewidgetitem3.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(0, 0, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        __qtablewidgetitem4.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(0, 1, __qtablewidgetitem4)
        __qtablewidgetitem5 = QTableWidgetItem()
        __qtablewidgetitem5.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(0, 2, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        __qtablewidgetitem6.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(1, 0, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        __qtablewidgetitem7.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(1, 1, __qtablewidgetitem7)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(1, 2, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        __qtablewidgetitem9.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(2, 0, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        __qtablewidgetitem10.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(2, 1, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        __qtablewidgetitem11.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(2, 2, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        __qtablewidgetitem12.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(3, 0, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        __qtablewidgetitem13.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(3, 1, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        __qtablewidgetitem14.setTextAlignment(Qt.AlignCenter);
        self.external_Interfaces.setItem(3, 2, __qtablewidgetitem14)
        self.external_Interfaces.setObjectName(u"external_Interfaces")
        self.external_Interfaces.setGeometry(QRect(10, 40, 331, 132))
        self.external_Interfaces.setStyleSheet(u"")
        self.external_Interfaces.setFrameShape(QFrame.Shape.Box)
        self.external_Interfaces.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.external_Interfaces.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.external_Interfaces.setAlternatingRowColors(True)
        self.external_Interfaces.setRowCount(4)
        self.external_Interfaces.horizontalHeader().setMinimumSectionSize(20)
        self.external_Interfaces.horizontalHeader().setDefaultSectionSize(103)
        self.external_Interfaces.horizontalHeader().setStretchLastSection(True)
        self.external_Interfaces.verticalHeader().setVisible(False)
        self.external_Interfaces.verticalHeader().setDefaultSectionSize(26)
        self.label = QLabel(self.tab_4)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 10, 151, 16))
        self.label.setFont(font1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.groupBox_6 = QGroupBox(self.tab_3)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 10, 331, 91))
        self.groupBox_6.setFont(font1)
        self.label_8 = QLabel(self.groupBox_6)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 30, 61, 16))
        self.label_8.setFont(font)
        self.label_9 = QLabel(self.groupBox_6)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 60, 49, 16))
        self.label_9.setFont(font)
        self.settings_NanonisIP = QLineEdit(self.groupBox_6)
        self.settings_NanonisIP.setObjectName(u"settings_NanonisIP")
        self.settings_NanonisIP.setGeometry(QRect(100, 30, 113, 21))
        self.settings_NanonisIP.setFont(font)
        self.settings_NanonisIP.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.settings_NanonisPort = QLineEdit(self.groupBox_6)
        self.settings_NanonisPort.setObjectName(u"settings_NanonisPort")
        self.settings_NanonisPort.setGeometry(QRect(100, 60, 113, 21))
        self.settings_NanonisPort.setFont(font)
        self.settings_NanonisPort.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 181, 171))
        self.groupBox_2.setFont(font1)
        self.status_Status = QLineEdit(self.groupBox_2)
        self.status_Status.setObjectName(u"status_Status")
        self.status_Status.setEnabled(False)
        self.status_Status.setGeometry(QRect(10, 20, 161, 21))
        self.status_Status.setFont(font)
        self.status_Status.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.status_Status.setReadOnly(False)
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 90, 47, 14))
        self.label_3.setFont(font)
        self.status_Setpoint = QLineEdit(self.groupBox_2)
        self.status_Setpoint.setObjectName(u"status_Setpoint")
        self.status_Setpoint.setEnabled(False)
        self.status_Setpoint.setGeometry(QRect(10, 110, 131, 21))
        self.status_Setpoint.setFont(font)
        self.status_Setpoint.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 140, 61, 16))
        self.label_7.setFont(font)
        self.status_Feedback = QPushButton(self.groupBox_2)
        self.status_Feedback.setObjectName(u"status_Feedback")
        self.status_Feedback.setGeometry(QRect(80, 140, 91, 24))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 107))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush)
        brush1 = QBrush(QColor(255, 255, 255, 135))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush1)
        self.status_Feedback.setPalette(palette)
        self.status_Feedback.setFont(font)
        self.status_Refresh = QPushButton(self.groupBox_2)
        self.status_Refresh.setObjectName(u"status_Refresh")
        self.status_Refresh.setGeometry(QRect(150, 110, 21, 24))
        self.status_Refresh.setFont(font)
        self.status_Connect = QPushButton(self.groupBox_2)
        self.status_Connect.setObjectName(u"status_Connect")
        self.status_Connect.setGeometry(QRect(10, 50, 71, 24))
        self.status_Connect.setFont(font)
        self.status_Disconnect = QPushButton(self.groupBox_2)
        self.status_Disconnect.setObjectName(u"status_Disconnect")
        self.status_Disconnect.setGeometry(QRect(90, 50, 81, 24))
        self.status_Disconnect.setFont(font)
        self.status_Disconnect.setStyleSheet(u"")
        self.status_Log = QPlainTextEdit(self.centralwidget)
        self.status_Log.setObjectName(u"status_Log")
        self.status_Log.setEnabled(True)
        self.status_Log.setGeometry(QRect(10, 340, 551, 121))
        self.status_Log.setReadOnly(True)
        Aunis.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(Aunis)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 570, 33))
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        Aunis.setMenuBar(self.menubar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuHelp.addAction(self.menuManualHelp)
        self.menuHelp.addAction(self.menuAboutHelp)
        self.menuFile.addAction(self.menuSaveFile)
        self.menuFile.addAction(self.menuLoadFile)

        self.retranslateUi(Aunis)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Aunis)
    # setupUi

    def retranslateUi(self, Aunis):
        Aunis.setWindowTitle(QCoreApplication.translate("Aunis", u"Aunis - Nanonis Control & Scripting Interface", None))
        self.menuAboutHelp.setText(QCoreApplication.translate("Aunis", u"About", None))
        self.menuManualHelp.setText(QCoreApplication.translate("Aunis", u"Manual", None))
        self.menuSaveFile.setText(QCoreApplication.translate("Aunis", u"Save", None))
        self.menuLoadFile.setText(QCoreApplication.translate("Aunis", u"Load", None))
        self.scripting_Run.setText(QCoreApplication.translate("Aunis", u"Run", None))
        self.scripting_Stop.setText(QCoreApplication.translate("Aunis", u"Stop", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("Aunis", u"Scripting", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("Aunis", u"Lateral", None))
        self.tipman_Yminus.setText(QCoreApplication.translate("Aunis", u"Y-", None))
        self.tipman_Xplus.setText(QCoreApplication.translate("Aunis", u"X+", None))
        self.tipman_Xminus.setText(QCoreApplication.translate("Aunis", u"X-", None))
        self.tipman_Yplus.setText(QCoreApplication.translate("Aunis", u"Y+", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("Aunis", u"Vertical", None))
        self.tipman_Zminus.setText(QCoreApplication.translate("Aunis", u"Z-", None))
        self.tipman_Zplus.setText(QCoreApplication.translate("Aunis", u"Z+", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("Aunis", u"Step Size", None))
        self.label_4.setText(QCoreApplication.translate("Aunis", u"\u0394x (\u00c5):", None))
        self.label_5.setText(QCoreApplication.translate("Aunis", u"\u0394y (\u00c5):", None))
        self.label_6.setText(QCoreApplication.translate("Aunis", u"\u0394z (\u00c5):", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("Aunis", u"Tip Manipulation", None))
        ___qtablewidgetitem = self.external_Interfaces.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Aunis", u"Name", None));
        ___qtablewidgetitem1 = self.external_Interfaces.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Aunis", u"IP Adress", None));
        ___qtablewidgetitem2 = self.external_Interfaces.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Aunis", u"Port", None));

        __sortingEnabled = self.external_Interfaces.isSortingEnabled()
        self.external_Interfaces.setSortingEnabled(False)
        self.external_Interfaces.setSortingEnabled(__sortingEnabled)

        self.label.setText(QCoreApplication.translate("Aunis", u"External TCP Interfaces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("Aunis", u"External", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("Aunis", u"Nanonis TCP Interface", None))
        self.label_8.setText(QCoreApplication.translate("Aunis", u"IP Adress:", None))
        self.label_9.setText(QCoreApplication.translate("Aunis", u"Port:", None))
        self.settings_NanonisIP.setInputMask(QCoreApplication.translate("Aunis", u"000.000.000.000", None))
        self.settings_NanonisIP.setText(QCoreApplication.translate("Aunis", u"127.0.0.1", None))
        self.settings_NanonisPort.setInputMask(QCoreApplication.translate("Aunis", u"000000", None))
        self.settings_NanonisPort.setText(QCoreApplication.translate("Aunis", u"6501", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("Aunis", u"Settings", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("Aunis", u"Status", None))
        self.status_Status.setText(QCoreApplication.translate("Aunis", u"Disconnected", None))
        self.label_3.setText(QCoreApplication.translate("Aunis", u"Setpoint:", None))
        self.label_7.setText(QCoreApplication.translate("Aunis", u"Feedback:", None))
        self.status_Feedback.setText(QCoreApplication.translate("Aunis", u"-", None))
        self.status_Refresh.setText(QCoreApplication.translate("Aunis", u"\u27f3", None))
        self.status_Connect.setText(QCoreApplication.translate("Aunis", u"Connect", None))
        self.status_Disconnect.setText(QCoreApplication.translate("Aunis", u"Disconnect", None))
        self.menuHelp.setTitle(QCoreApplication.translate("Aunis", u"Help", None))
        self.menuFile.setTitle(QCoreApplication.translate("Aunis", u"File", None))
    # retranslateUi

